Length branch
cchobi/Similarity-0314 pull request #1
Opened 2024-07-03 23:51 UTC by cchobi

두 문자열 길이 검사하는 코드입니다.

2024-07-03 23:55 UTC, jun6ak requested changes

2024-07-03 23:55 UTC, jun6ak commented on Similar/similar.cpp
> +		}
길이를 얻는 과정이 함수화 되어도 좋을 것 같습니다!

2024-07-04 00:00 UTC, joo0-hong requested changes

2024-07-04 00:00 UTC, joo0-hong commented on Similar/similar.cpp
> +		if (longLen == shortLen) return 60;
60이라는 값이 여러 번 쓰이고 있어서 별도 define해주면 어떨까요??

2024-07-04 00:06 UTC, cchobi commented on Similar/similar.cpp
> +		}
길이를 구하는 부분을 getLongShortLength()로 추출하였습니다.

2024-07-04 00:09 UTC, cchobi commented on Similar/similar.cpp
> +		if (longLen == shortLen) return 60;
추가 완료하였습니다.

2024-07-04 00:16 UTC, jun6ak approved these changes

2024-07-04 00:16 UTC, joo0-hong approved these changes

2024-07-04 00:16 UTC, merged